services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shopper-api

  app:
    image: paulolemes/shopper-api:1.4
    depends_on:
      - db
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
    ports:
      - "3333:3333"
    networks:
      - shopper-api
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

volumes:
  pgdata:
networks:
  shopper-api:
    driver: bridge
